# Generated by Django 6.0.6 on 2026-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='Devise'),
        ),
    ]
