# Generated by Django 6.0.6 on 2026-08-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bankaccount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('nl', 'Nederlands')], default='fr', max_length=5, verbose_name='Langue'),
        ),
    ]
