# Generated by Django 6.0.6 on 2026-08-04 14:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='unblock_fee_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frais de déblocage déjà payés'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='unblock_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frais de déblocage (total à payer)'),
        ),
    ]
