# Generated by Django 6.0.6 on 2026-08-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bankaccount_unblock_fee_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RibRecord',
            fields=[
            ],
            options={
                'verbose_name': 'RIB / IBAN',
                'verbose_name_plural': 'RIB / IBAN (tous les comptes)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.bankaccount',),
        ),
    ]
