# Generated by Django 6.0.6 on 2026-08-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ribrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='transfers_enabled',
            field=models.BooleanField(default=True, verbose_name='Virements autorisés'),
        ),
    ]
