# Generated by Django 6.0.6 on 2026-08-03 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_account_b00314_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En cours de validation'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=15, verbose_name='Statut'),
        ),
    ]
